require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
  Pry.start
end

desc "Squirt out some emojis"
task :emojis do
  puts "🤯" * 10
end
